import { AuthProvider } from "./utils/context/authContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body style={{ margin: 0 }}>{children}</body>
      </html>
    </AuthProvider>
  );
}
